### ISSUE TITLE
Export single-entry modules?

### ISSUE THREAD

**Issue by dy** [davidfig/intersects#1]
Hello @davidfig!

I just had a hard quest of finding line-line intersection package with simple API. Turns out all of them whether have complex API (therefore slow performance) or doubtful algorithms. The closest one I found is [segseg](https://www.npmjs.com/package/segseg), but it works for segments, not lines.

Your module seems to be perfect for that task, the only blocker - for performance/API reasons it would be nice to be able to require just a single intersection function (similar to [color-space](https://github.com/colorjs/color-space) or [101](https://github.com/tjmehta/101)), eg.

```js
let isec = require('simple-intersect/line-line')
```

isn't that? Otherwise it requires the whole set of functions that are not neccessarily to be used in bundle.

If you think that is a good idea I can come up with a PR.

**Comment by davidfig** [comment]
Sure. Reducing complexity was the goal of this library. Happy to review a PR that breaks out the individual functions. Sounds like a lot of work but if you think it’s worth it then go for it.

**Comment by dy** [comment]
@davidfig added you as an owner https://www.npmjs.com/package/intersects

I suggest
* [x] add me to the contributors (I can do the rest if you prefer)
* [x] rename `simple-intersect` to `intersects`
* [x] deprecate `simple-intersect` with reference to `intersects`
* [ ] ~~add `tolerance` param for box-box intersection function (although possibly belongs not here)~~
* [x] enhancing readme (badges, license, API etc.)

**Comment by davidfig** [comment]
Not sure about the tolerance. If we add it to box-box, should we add it to all the functions? I usually handle tolerance in the client code.

I don't usually put badges in the readme. Add what you think is appropriate.
