### ISSUE TITLE
Angle?

### ISSUE THREAD

**Issue by tangjin0418** [davidfig/intersects#16]
i am trying use oval+circle
but my oval need a angle

**Comment by davidfig** [comment]
Why an angle? Usually an ellipse has a horizontal radius and vertical radius. If it's a rotated ellipse, then you'll need to do more work. This library doesn't handle transforms.

**Comment by tangjin0418** [comment]
example?
my math is not good

**Comment by davidfig** [comment]
Usually an ellipse is defined as ellipse(centerX, centerY, radiusX, radiusY). How is your ellipse defined?

**Comment by tangjin0418** [comment]
my is 50,50,0.8*72*72

**Comment by davidfig** [comment]
I'm not sure. It could be the ellipse's angular eccentricity (https://math.stackexchange.com/questions/481632/how-to-interpret-angle-of-ellipse-in-drawing-guide/481644) or perhaps the ratio of rx to ry, but either way you'd need the radius for it to make sense. But I'm not a mathematician, so I might be missing something :)
