### ISSUE TITLE
polygonPolygon doesn't work for concave polygons

### ISSUE THREAD

**Issue by thisredone** [davidfig/intersects#4]
```javascript
let p1 = [1306, 604, 1628, 610, 1638, 548, 1582, 492, 1628, 468, 1634, 402, 1592, 388, 1564, 444, 1520, 442, 1490, 402, 1460, 402, 1448, 468, 1378, 514, 1310, 544];
let p2 = [1294, 272, 1384, 272, 1384, 476, 1294, 476];
polygonPolygon(p1, p2)
// true
```
![image](https://user-images.githubusercontent.com/1191844/45601374-54ce9a00-ba0c-11e8-9da1-976b8539bc36.png)

**Comment by davidfig** [comment]
Concave polygon collisions are a more difficult algorithm and are currently not supported. (I updated the documentation to reflect this.) The best way to handle these collisions is to break down the concave polygon into convex polygons and then test those convex polygons. You can check out this library: https://github.com/schteppe/poly-decomp.js

**Comment by thisredone** [comment]
Sure thing. Thanks for the link
