### ISSUE TITLE
False-positive on polygon-point

### ISSUE THREAD

**Issue by Rob-ot** [davidfig/intersects#5]
Hey, thank you for the useful library!

I'm having an issue where polygonPoint is giving true for a point outside the polygon.

Here's the code, I expect this to return `false` but it gives `true`, v2.2.1:
```javascript
polygonPoint([27, 47, 8, 47, 8, 46, 27, 46], 14, 45)
```

Here it is visualized, red is the point:
![screen shot 2018-10-01 at 1 16 22 pm](https://user-images.githubusercontent.com/409228/46313325-67a0ad00-c57c-11e8-8502-ff771f7751ee.png)

Thanks!

**Comment by davidfig** [comment]
The polygonPoint function uses the pointLine function to test the point along the edges of the polygon. The pointLine has a default tolerance=1, so if the point is within 1 unit of the line, then it triggers true. Your example has the point within one unit of the line, which is what causes it to be true.

I updated the library in v.2.3.0 to include a tolerance option in pointPolygon. If you change the tolerance to 0.5 it should work in your example.

**Comment by Rob-ot** [comment]
Wow that was fast! The fix works perfectly, I have to use a pretty low tolerance for my situation (0.001) but it works great.

Thank you so much!
