### ISSUE TITLE
Any way to intersect with a circle line?

### ISSUE THREAD

**Issue by ctlaux** [davidfig/intersects#9]
The circle/line intersection routine seems to take the circle as a disk. Is there any way to intersect the circle as a line of specified radius with a straight line?

**Comment by davidfig** [comment]
Not sure I understand the question. What are the two shapes you want to intersect? Can you give me pseudo code?

**Comment by ctlaux** [comment]
I am calling this routine: `intersects.circleLine( ... r, ... )`

It seems to return `true` for any line of which a part lies inside the disk of radius r. But I only want to get `true` for lines that intersect a circle line (i.e. not a filled disk) of radius r.

I'm not sure how else to express this, I hope it makes sense.

**Comment by davidfig** [comment]
Ah. That makes sense. Took a bit of thinking, but here's code for how to do it (pseudo code as I haven't tested it):
```js
const thickness = 1 // thickness of circle line
if (intersects.circleLine(cx, cy, r, x1, y1, x2, y2) && 
   !(intersects.circlePoint(cx, cy, r - thickness, x1, y1) && intersects.circlePoint(cx, cy, r - thickness, x2, y2)
)
{
   console.log('line intersects with outline of circle')
}
```
The only case where the line intersects the circle but not the outline is when the starting and ending points of the line are both inside the radius of the circle (less the thickness of the outline's line). 

Hopefully that helps!

**Comment by ctlaux** [comment]
Yes, that worked! I had a similar idea using two calls to `circleLine` but that failed in practice.

Thanks for the help, and thanks for a great library!

**Comment by dy** [comment]
Intersect with circumference - I guess there is a sense for a separate method.
